# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go env -w CGO_ENABLED=0
    - go mod download
    # you may remove this if you don't need go generate
#    - go generate ./...
builds:
  - binary: main
    id: gomain
    goos:
     - macos
    # - windows
