initialRootNumNodes: 1000
numEachLayer: 5
randomInvite: true
numLayers: 9
numNodes: 1000000
day: 10
dayProbability: 
  - 40
  - 30
  - 20
  - 10
rootInviteeNum:
  - 10
  - 20
  - 30
rootInvitorsProbability:
  - 40
  - 30
  - 30
inviteeNum:
  - 10
  - 20
  - 2
  - 5
  - 3
  - 2
  - 10
  - 5
  - 8
  - 0
  - 7
  - 1
  - 1
  - 2
invitorsProbability:
  - 1.5
  - 30
  - 3
  - 2
  - 5
  - 5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 1
  - 0.3
  - 1
  - 1
  - 1

depositNum:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
depositProbability:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10  
  - 10
  - 10
  - 10
  - 10