initialRootNumNodes: 10
numEachLayer: 5
numLayers: 9
numNodes: 10000
inviteeNum:
  - 10
  - 2
  - 3
  - 5
  - 8
  - 10
  - 7
  - 1
  - 1
  - 2
invitorsProbability:
  - 10
  - 10
  - 7
  - 1
  - 1
  - 1  
  - 1
  - 1
  - 1
  - 1

depositNum:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
depositProbability:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10  
  - 10
  - 10
  - 10
  - 10