initialRootNumNodes: 10
numEachLayer: 5
randomInvite: true
numLayers: 9
numNodes: 10000
inviteeNum:
  - 10
  - 0
  - 2
  - 5
  - 3
  - 2
  - 0
  - 5
  - 8
  - 0
  - 7
  - 1
  - 1
  - 2
invitorsProbability:
  - 1.5
  - 0.3
  - 0.3
  - 0.2
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 1
  - 0.3
  - 1
  - 1
  - 1

depositNum:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
  - 1000
depositProbability:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10  
  - 10
  - 10
  - 10
  - 10